spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  server:
    servlet:
      session:
        persistent: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  data:
    mongodb:
      uri: mongodb://localhost:27017/team3
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 500MB

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
server:
  port: 8081
  tomcat:
    max-swallow-size: -1
    max-file-upload-count: 50
    additional-tld-skip-patterns: "*.jar"
    max-http-form-post-size: -1
map:
  kakao:
    key: ${KAKAO_MAP_KEY:}